config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :subjects, only: [:new, :create] do
      resources :memories
    end
  end

  namespace :api do
    match '/users/:user_id/subjects/family', to: 'subjects#family', via: 'get'
    match '/users/:user_id/subjects/friends', to: 'subjects#friends', via: 'get'
    match '/users/:user_id/subjects/coworkers', to: 'subjects#coworkers', via: 'get'

    match '/released_users/:released_user_id/memorialized/:user_id/memories', to: 'released_memories#index', via: 'get'

    resources :users, only: [:show] do
      resources :subjects, only: [:show, :index] do
        resources :memories, only: [:show, :index]
      end
    end
  end

  root "static_pages#home"
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/twilio/process_sms', to:'twilio#process_sms', via: 'post'
  # get "/remember/:user_id", to: 'remember#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_validation do 
    if self.phone_number
      self.phone_number = phone_number.gsub(/[^0-9]/, "") 
      self.phone_number.slice!(0) if self.phone_number[0] == '1' && self.phone_number.length > 10
    end
  end
  before_create :create_remember_token
  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :email, presence:true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, uniqueness: true
  validates :legacy_contact_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, allow_blank:true
  validates :password, length: { minimum: 6 }
  validates :phone_number, presence:true, uniqueness:true, length: { is:10 }
  has_secure_password

  has_many :subjects, dependent: :destroy


  def full_name
    "#{first_name} #{last_name}"
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def get_memorialized_user_by_twilio_number(twilio_number)
    self.relationships.each do |relationship|
      return User.find(relationship.memorialized_id) if relationship.twilio_number == twilio_number
    end
  end

  def get_memorializing_twilio_number(other_user)
    relationship = self.relationships.find_by(memorialized_id:other_user.id)
    return relationship.twilio_number if relationship
  end

  def memories
    subjects = self.subjects
    subjects.map {|subject| subject.memories }.flatten
  end

  def as_json(options = {})
    super(options.merge({ except: [:password_digest, :remember_token, :phone_number, :created_at, :updated_at, :legacy_contact_email] })) 
  end 

  private
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user

  def show
    @user = User.find(params[:id])
    render json: @user
  end

  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:show, :update, :edit]
  before_action :correct_user, only: [:show, :update, :edit]

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

# {30=> [#<Memory:0x007fba9855f488 id: 13, content: "Sunnyside fo evah!", user_id: 29, memorialized_user_id: 30, ...],
#  31=> [#<Memory:0x007fba9854bf00 id: 12, content: "Love this guy!", user_id: 29, memorialized_user_id: 31, ...]}

  def show
    @user = User.find(params[:id])
    @subjects = @user.subjects
    # @memories_hash = @user.memories.group_by do |memory|
    #   memory.subject_id
    # end
  end


  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Legacy App!"
      redirect_to @user
    else
      render 'new'
    end

  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number, :legacy_contact_email)
  end

  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="black-background-sign-up">


    <div class="sign-up-form">
    <h1>Update your profile</h1>

    <%= form_for(@user, :html => {:class => "pure-form, pure-form-aligned"}) do |f| %>
      <%= render 'shared/error_messages' %>

      <div class="pure-control-group">
    <!--   <%= f.label :email %>
     -->  <%= f.text_field :email, :placeholder => 'Email' %>
    </div>

      <div class="pure-control-group">
    <!--   <%= f.label :first_name %>
     -->  <%= f.text_field :first_name, :placeholder => 'First Name' %>
    </div>

      <div class="pure-control-group">
    <!--   <%= f.label :last_name %>
     -->  <%= f.text_field :last_name, :placeholder => 'Last Name' %>
    </div>


      <div class="pure-control-group">
    <!--   <%= f.label :phone_number, 'Phone Number' %>
     -->  <%= f.text_field :phone_number, :placeholder => 'Phone Number' %>
    </div>

        <div class="pure-control-group">
    <!--       <%= f.label :legacy_contact_email, 'Contact Email Address (in case of death)' %>
     -->      <%= f.text_field :legacy_contact_email, :placeholder => 'Contact Email Address (in case of death)' %>
       </div>

      <div class="pure-control-group">
    <!--   <%= f.label :password %>
     -->  <%= f.password_field :password, :placeholder => 'Password' %>
    </div>

      <div class="pure-control-group">

    <!--   <%= f.label :password_confirmation %>
     -->  <%= f.password_field :password_confirmation, :placeholder => 'Confirmation' %>
    </div>

    <!-- <div class="pure-controls">
     -->  <%= f.submit "Save changes", :class => "pure-button, pure-button-primary" %>
    <!-- </div>
     -->
    <% end %>

    </div>
</div>

<div class='black-bottom-signup'>
</div>
 <p class="footer-logo">power by You</p>

app/views/users/new.html.erb
<div class="black-background-sign-up">
  
  <div class="sign-up-form">

  <h1 id="user-new-title">myJourney</h1>

  <%= form_for(@user, :html => {:class => "pure-form, pure-form-aligned"}) do |f| %>

    <%= render './shared/error_messages' %>

    <div class="pure-control-group">
<!--       <%= f.label :first_name %>
 -->      <%= f.text_field :first_name, :placeholder => 'First Name' %>
    </div>

    <div class="pure-control-group">
<!--       <%= f.label :last_name, 'Last Name' %>
 -->      <%= f.text_field :last_name, :placeholder => 'Last Name' %>
    </div>

    <div class="pure-control-group">
<!--       <%= f.label :email, 'Email' %>
 -->      <%= f.text_field :email, :placeholder => 'Email' %>
   </div>

    <div class="pure-control-group">
<!--       <%= f.label :phone_number, 'Phone Number' %>
 -->      <%= f.text_field :phone_number, :placeholder => 'Phone Number' %>
   </div>


    <div class="pure-control-group">
<!--       <%= f.label :legacy_contact_email, 'Contact Email Address (in case of death)' %>
 -->      <%= f.text_field :legacy_contact_email, :placeholder => 'Contact Email (in case of death)' %>
   </div>

    <div class="pure-control-group">
<!--       <%= f.label :password, 'Password' %>
 -->      <%= f.password_field :password, :placeholder => 'Password' %>
   </div>

    <div class="pure-control-group">
<!--       <%= f.label :password_confirmation, 'Confirmation' %>
 -->      <%= f.password_field :password_confirmation, :placeholder => 'Confirmation' %>
   </div>

    <%= f.submit 'Create Account', :class => 'pure-button, pure-button-primary' %>
  <% end %>
  </div>

</div>
<div class='black-bottom-signup'>
</div>
 <p class="footer-logo">power by You</p>

app/views/users/show.html.erb
<head>
  <link rel="stylesheet" href="//assets.ziggeo.com/css/ziggeo-betajs-player.min.css" />
  <script src="//assets.ziggeo.com/js/ziggeo-json2-betajs-player.min.js"></script>
  <script>ZiggeoApi.token = "2deecf9c00f2077ad7ca6e9e383b5c92";</script>
</head>


<div class="container">
  <div class="black-background"> </div>

  <div class="pic-circles-section">
    <div class="image-area"> </div>
    <div class="profile-pic"> <p>+ Upload Photo</p> </div>
    <div class="fm-circle"> <h3>fm</h3> </div>
    <div class="fr-circle"> <h3>fr</h3> </div>

    <%= link_to new_user_subject_path(@user) do %>
      <div class="create-circle-small"> <h3>+</h3> </div>
    <% end %>

    <div class="create-circle"><h3>+<h3></div> 

  </div> <!-- end pic-circles-section div -->

</div> <!-- end container div -->


<!-- //**************DATA FOR DOM MANIPULATIONS******************************/ -->

<div class="data">
  <div class="black-background-data"> </div>
  <ul id="media-stash"> </ul>

  <% @subjects.each do |subject| %>
  <%= link_to("Create Video", new_user_subject_memory_path(user_id:@user.id, subject_id:subject.id), id: 'video-link-' + subject.id.to_s)%>
  <% end %>
</div>