config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :subjects, only: [:new, :create] do
      resources :memories
    end
  end

  namespace :api do
    match '/users/:user_id/subjects/family', to: 'subjects#family', via: 'get'
    match '/users/:user_id/subjects/friends', to: 'subjects#friends', via: 'get'
    match '/users/:user_id/subjects/coworkers', to: 'subjects#coworkers', via: 'get'

    match '/released_users/:released_user_id/memorialized/:user_id/memories', to: 'released_memories#index', via: 'get'

    resources :users, only: [:show] do
      resources :subjects, only: [:show, :index] do
        resources :memories, only: [:show, :index]
      end
    end
  end

  root "static_pages#home"
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/twilio/process_sms', to:'twilio#process_sms', via: 'post'
  # get "/remember/:user_id", to: 'remember#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>myJourney</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%# <link rel="stylesheet" href="https://yui.yahooapis.com/pure/0.6.0/pure-min.css"> %>
    <link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700,700italic|Ubuntu' rel='stylesheet' type='text/css'>
  </head>
  <body>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <nav>

          <%= link_to current_user, class: 'logo-link' do %>
            <span class="my-span">my</span><span class="journey-span">Journey</span>
          <% end %>
          
      <% if signed_in? %>
         <%= link_to "Log Out", signout_path, method: 'delete', class: 'right' %>


          <%= link_to edit_user_path(current_user) do %>
            <i class="fa fa-cog fa-lg"></i>
          <% end %>

        <% else %>
          <%= link_to "Sign in", signin_path, class: 'right' %>
        <% end %>
    </nav>
    <%= yield %>

  </body>
</html>